module.exports = {
  UserRepository: require("./user-repository"),
  CreditsRepository: require("./credits-repository"),
  UserJourneyRepository: require("./user-journey-repository"),
  ServerManagementRepository:require("./server-management-repository"),
  DataCenterRepository:require("./data-center-repository"),
  LicenceRepository: require("./licence-repository"),
  TrunkRepository: require("./trunk-repository"),
  AgentRepository: require("./agent-repository"),
  ExtensionRepository: require("./extension-repository"),
  OperatorRepository: require("./operator-repository"),
  CodecRepository: require("./codec-repository"),
  DataCenterRepository:require("./data-center-repository"),
  PromptRepository:require("./prompt-repository"),
  NumbersRepository:require("./numbers-repository"),
  DIDUserMappingRepository:require("./did-user-mapping-repository"),
  NumberFileListRepository:require("./number-filelist-repository"),
  NumberStatusRepository:require('./number-status-repository'),
  MemberScheduleRepo:require('./member-schedule-repository'),
  CountryCodeRepository:require("./country-code-repository"),
  IVRDataRepository:require("./ivr-data-repository"),
  IVRRepository:require("./ivr-repository"),
  FlowControlRepository:require("./flow-control-repository"),
  FlowEdgesRepository:require("./flow-edge-repository"),
  FlowJsonRepository:require("./flow-json-repository"),
  FlowRepository:require("./flows-repository"),
  AclSettingsRepository:require("./acl-settings-repository"),
  CompanyRepository:require("./company-repository"),
  TimezoneRepository: require("./timezone-repository"),
  LanguageRepository: require("./language-repository"),
  CodecsRepository: require("./codec-repository"),
  ModuleRepository: require("./module-repository"),
  OperatorsRepository: require("./operator-repository"),
  DownloadReportRepository: require("./download-report-repository"),
  IncomingSummaryRepository: require("./incoming-summary-repository"),
  HandleFileSaveRepository: require("./handle-FileSave-repositoy"),
  CallCentreRepository: require("./call-centre-repository"),
  SubUserLicenceRepository:require("./sub-user-licence-repository"),
  VoicePlansRepository: require("./voice-plans-repository"),
  TelephonyProfileRepository: require("./telephony-profile-repository"),
  TelephonyProfileItemsRepository: require("./telephony-profile-items-repository"),
  SubscriberRepository: require("./subscriber-repository"),
  AgentGroupRepository: require("./agent-group-repository"),
  AgentGroupAgentRepository:require("./agent-group-agents-repository")
};
