
module.exports = {
    UserController:require("./user-controller"),
    CreditController: require("./credits-controller"),
    UserJourneyController: require("./user-journey-controller"),
    ServerManagementController: require("./server-management-controller"),
    DataCenterController:require("./data-center-controller"),
    TrunkController: require("./trunk-controller"),
    AgentController:require("./agent-controller"),
    CompanyController:require("./company-controller"),
    OperatorController:require("./operator-controller"),
    CodecController:require('./codec-controller'),
    PromptController:require("./prompt-controller"),
    NumbersController:require("./numbers-controller"),
    TrunkController: require("./trunk-controller"),
    IVRController: require("./ivr-controller"),
    CityController: require("./city-controller"),
    StateController: require("./state-controller"),
    UtilityController: require("./utility-controller"),
    LanguageController: require("./language-controller"),
    CodecsController: require("./codec-controller"),
    ModuleController: require("./module-controller"),
    OperatorController: require("./operator-controller"),
    ExportListController: require("./export-list-controller"),
    DownloadReportController: require("./download-report-controller"),
    IncomingSummaryController: require("./incoming-summary-controller"),
    HandleFileSaveController: require("./handleFileSave-controller"),
    CallCentreController: require("./call-centre-controller"),
    CountryCodeController: require("./country-code-controller"),
}