const { ContactGroup, SmsWebhooks } = require("../../shared/c_db");

module.exports = {
    UserController:require("./user-controller"),
    CreditController: require("./credits-controller"),
    UserJourneyController: require("./user-journey-controller"),
    ServerManagementController: require("./server-management-controller"),
    DataCenterController:require("./data-center-controller"),
    TrunkController: require("./trunk-controller"),
    AgentController:require("./agent-controller"),
    AgentGroupController:require('./agent-group-controller'),
    CompanyController:require("./company-controller"),
    OperatorController:require("./operator-controller"),
    CodecController:require('./codec-controller'),
    PromptController:require("./prompt-controller"),
    NumbersController:require("./numbers-controller"),
    TrunkController: require("./trunk-controller"),
    IVRController: require("./ivr-controller"),
    CityController: require("./city-controller"),
    StateController: require("./state-controller"),
    UtilityController: require("./utility-controller"),
    LanguageController: require("./language-controller"),
    CodecsController: require("./codec-controller"),
    ModuleController: require("./module-controller"),
    OperatorController: require("./operator-controller"),
    ExportListController: require("./export-list-controller"),
    DownloadReportController: require("./download-report-controller"),
    IncomingSummaryController: require("./incoming-summary-controller"),
    HandleFileSaveController: require("./handleFileSave-controller"),
    CallCentreController: require("./call-centre-controller"),
    AclSettingsController:require("./acl-setting-controller"),
    CountryCodeController: require("./country-code-controller"),
    NumberFileListController: require("./number-fileList-controller"),
    VoicePlanController: require("./voice-plans-controller"),
    ExtensionController: require("./extension-controller"),
    CallsController: require("./calls-controller"),
    QueueController: require("./queue-controller"),
    IncomingReportController: require("./incoming-report-controller"),
    DidAllocateHistoryController: require("./did-allocate-history-controller"),
    DidRemoveHistoryController: require("./did-remove-history-controller"),
    OutgoingCallsController: require('./outgoing-calls-controller'),
    RemarkStatusController: require('./remark-status-controller'),
    RemarksController: require('./remarks-controller'),
    VoiceCampaignController:require("./voice-campaign-controller"),
    BreakController: require("./break-controller"),
    ContactGroupController: require("./contact-group-controller"),
    ContactGroupMemberController: require("./contact-group-member-controller"),
    WebhookController: require("./webhook-controller"),
    SmsWebhookController:require("./sms-webhook-controller"),
    ScriptsController: require("./scripts-controller"),
    GroupsController: require("./groups-controller"),
    LocationController: require("./locations-controller"),
    VoiceDialerController: require("./voice-dialer-controller"),
}