module.exports = {
    UserMiddleware: require('./user-middleware'),
    AuthMiddleware: require('./auth-middleware'),
    CallCentreMiddleware: require('./call-centre-middleware'),
    TrunksMiddleware: require('./trunk-middleware'),
    CountryCodeMiddleware: require('./country-code-middleware'),
    NumbersMiddleWare: require('./numbers-middleware'),
    IVRMiddleWare: require('./ivr-middleware'),
    OperatorMiddleware: require('./operator-middleware'),
    CallsMiddleware: require('./calls-middleware'),
    DataCenterMiddleware: require('./data-center-middleware'),
    ServerManagementMiddleware: require('./server-management-middleware'),
    ModuleMiddleware: require('./module-middleware'),
    AclSettingsMiddleware: require('./acl-settings-middleware'),
    NumberFileListMiddleware: require('./number-filelist-middleware'),
    AgentMiddleware: require('./agent-middleware'),
    AgentGroupMiddleware: require('./agent-group-middleware'),
    ExtensionMiddleware: require('./extension-middleware'),
    QueueMiddleware: require('./queue-middleware'),
    MemberScheduleMiddleware:require('./member-schedule-middleware'),
    PromptsMiddleware: require('./prompts-middleware'),
    CreditMiddleware: require('./credit-middleware'),
    IncomingReportMiddleware: require('./incoming-report-middleware'),
    DownloadReportMiddleware: require('./download-report-middleware'),
    CompanyMiddleware: require('./company-middleware'),
    VoicePlansMiddleware: require('./voice-plans-middleware')
}