module.exports = {
    UserRepository: require('./user-repository'),
    CompanyRepository: require('./company-repository'),
    CallCentreRepository: require('./call-centre-repository'),
    CodecRepository: require('./codec-repository'),
    TrunksRepository: require('./trunk-repository'),
    CountryCodeRepository: require('./country-code-repository'),
    NumbersRepository: require('./numbersRepository'),
    IVRRepository: require('./ivr-repository'),
    OperatorsRepository: require('./operator-repository'),
    CallsRepository: require('./calls-repository'),
    IVRDataRepository: require('./ivr-data-repository'),
    TimezoneRepository: require('./timezone-repository'),
    DataCenterRepository: require('./data-center-repository'),
    ServerManagementRepository: require('./server-management-repository'),
    ModuleRepository: require('./module-repository'),
    UserJourneyRepository: require('./user-journey-repository'),
    AclSettingRepository: require('./acl-settings-repository'),
    NumberFileListRepository: require('./number-filelist-repository'),
    NumberStatusRepository: require('./number-status-repository'),
    DIDUserMappingRepository: require('./did-user-mapping-repository'),
    AgentRepository: require('./agent-repository'),
    AgentGroupRepository: require('./agent-group-repository'),
    ExtentionRepository: require('./extention-repository'),
    AgentGroupMappingRepository: require('./agent-group-mapping-repository'),
    LicenceRepository: require('./licence-repository'),
    QueueRepository: require('./queue-repository'),
    FlowControlRepository:require('./flow-control-repository'),
    HandleFileSaveRepository:require('./handle-FileSave-repositoy'),
    MemberScheduleRepository:require("./member-schedule-repository"),
    PromptRepository:require("./prompt-repository"),
    FLowRepository: require('./flows-repository'),
    FlowEdgesRepository: require('./flow-edge-repository'),
    LanguageRepository: require('./language-repository'),
    SubUserLicenceRepository: require('./sub-user-licence-repository'),
    FlowAsteriskRepository: require('./flow-asterisk-repository')
}